### ISSUE TITLE
Can't draw rectangle on picture for the first time.

### ISSUE THREAD

**Issue by fanweiGit** [mircea21S/RichCanvas#11]
Hi,
Today is our second communication, Trouble you again. haha~
When I add an image to the canvas, and set IsSelectable = false and IsDraggable = false , and then want to be able to draw a rectangle on the image, the first time I always fail to draw a rectangle, after the first time it's normal. How can I fix this, is there a problem between the priority of moving the picture and drawing the rectangle?
Best Wishes!

**Comment by fanweiGit** [comment]
![draw](https://user-images.githubusercontent.com/26829638/156884889-f9f0eb43-abd0-4197-8afc-6913271b8fce.gif)

**Comment by mircea21S** [comment]
Hi,

This is a bug which I just fixed with that commit.
Also should be in a new version soon on nuget.

Thank you
