### ISSUE TITLE
null reference exception when left-clicking

### ISSUE THREAD

**Issue by damonftl** [mircea21S/RichCanvas#13]
Hi, I've got your code mostly working, but I think I'm missing something. I'm trying to do something very simple - just want to use the zooming and panning functionality right now, and eventually drawing boxes on the images for cropping purposes.

We already have images loading and appearing, using the regular System Image control and setting the image's Uri in the view model. Here's how I have the xaml right now:

```
    <rc:RichItemsControl ItemsSource="{Binding RichCanvasItems}">
        <Image Source="{Binding ImageSource.Uri}"/>
    </rc:RichItemsControl>
```

And in the view model:

```
public ObservableCollection<IImageSource> RichCanvasItems { get; set; }

OnImageLoad(Uri uri) {
            if (RichCanvasItems == null) {
                RichCanvasItems = new ObservableCollection<IImageSource>();
            }
            RichCanvasItems.Clear();

            ImageSource.Uri = uri;
            RichCanvasItems.Add(ImageSource);
}
```

ImageSource's type is our own interface and just contains the uri for the image. This code actually all works, and the image is loaded and appears. I can zoom and pan it by holding control or space and the left mouse button. In fact I don't even need the ObservableCollection in that code above, it still works the same.

The problem is when I just left click on the image or the empty area around it. The program crashes with a null reference in RichCanvas.dll, so I can't quite see exactly what's going wrong. My guess is it's trying to select something or maybe draw the image even though it's already there? Thank you for any help.

**Comment by mircea21S** [comment]
Hi,

Yes, that's a problem in the library, the ```SelectedItems``` is initialized with the default value of ```IList``` which is null.
To fix that you should bind ```SelectedItems``` to an empty collection just to initialize it, as a workaround.

A fix will come soon with a new version on nuget also.

Thank you for reporting this bug.

**Comment by damonftl** [comment]
Thank you for the quick reply! Your solution worked.

I found that the SelectedItems observable collection also had to be a specific type, which is System.Windows.Controls.Image (as opposed to System.Drawing.Image) or it will also crash with an error about the type. That's likely because of how I have my particular collection set up in my xaml, but I figured I'd mention it in case anyone else runs across the same thing.

**Comment by mircea21S** [comment]
Yes, the collection type has to be the same as the ```DataContext``` property of the Control you're adding as a child. In your case the type of ```<Image>``` control. But you can have a base class there or ```object``` or you can handle it on your own, but anyway a fix will come and will have a default value which is not null.

**Comment by mircea21S** [comment]
v2.2.0 contains the fix
