### ISSUE TITLE
ItemContainer isn't moving and border is not showing

### ISSUE THREAD

**Issue by adwareapril** [mircea21S/RichCanvas#18]
Hello! I tried placing an Itemcontainer inside the richitemscontrol and when I try using drag and drop the item isn't moving.
Here's my code:
`  <richCanvas:RichItemsControl EnableGrid="True" GridSpacing="5" x:Name="TestCanvas" Scale="1" EnableSnapping="True">
                <richCanvas:RichItemContainer Width="65" Height="65" Foreground="Red" BorderBrush="Red" IsDraggable="True" IsSelectable="True" >
                    <TextBlock>Hello</TextBlock>
                </richCanvas:RichItemContainer>
            </richCanvas:RichItemsControl>
`

**Comment by mircea21S** [comment]
Hi!

You're right, the "drag and drop" functionality doesn't work in this case, but for a specific reason described in the  [documentation](https://github.com/mircea21S/RichCanvas/wiki/ItemContainer-Overview#transform) the container needs a RenderTransform and in your case when you specifically add it to the ItemsControl it doesn't have one.
So you need to add a TransformGroup exaclty how it's specified in the docs on your RichItemContainer.
