### ISSUE TITLE
Panning key while clicking on a clickable object now opens the object.

### ISSUE THREAD

**Issue by CommissarClippy** [mircea21S/RichCanvas#20]
Latest version changed this. Previous version gave the panning of the canvas priority over calling the on click of an object. Is there a binding that can change this back or is something broken?

**Comment by mircea21S** [comment]
Hi,

Yes... Thanks for catching that, I changed the mouse events and didn't pay attention to this. I changed them back to Preview events so now I catch the panning before click, this was the problem.

I will release a new v2.4.2 with this fix.
Thanks.

**Comment by CommissarClippy** [comment]
Okay, I will check the new version and let you know.
