### ISSUE TITLE
 Move the mouse to draw

### ISSUE THREAD

**Issue by naranghae** [mircea21S/RichCanvas#25]
Hello, I am using Rich Canvas. I have one question.
Is there a function to draw lines or Rectangle by moving the mouse? Or do I have to implement it myself?

**Comment by mircea21S** [comment]
Hi!

There is a function that does that. You can find more details here: https://github.com/mircea21S/RichCanvas/wiki/ItemsControl-Overview#drawing

I hope that answers your question.

Thanks!

**Comment by naranghae** [comment]
Thanks for the quick reply!

**Comment by mircea21S** [comment]
Hey, if this answered your question can you please close this issue? 

Thank you.
