### ISSUE TITLE
The names 'RichItemsControl' and 'RichItemContainer' seem to be reversed.

### ISSUE THREAD

**Issue by XMJLXMJL** [mircea21S/RichCanvas#27]
It seems that the meanings of the names 'RichItemsControl' and 'RichItemContainer' have been reversed.
Containers are like boxes that hold and organize stuff, such as Grid or StackPanel. Controls are the things you can interact with, such as Button or TextBox.
By the way, I'm just starting to learn WPF, so this might be a wrong suggestion

**Comment by mircea21S** [comment]
Hi!

It's hard to say what's what in terms of WPF as almost everything is a Control, you'll see more below, but I will try to give my 2 cents about the way I see these concepts inside my library.

So the way these concepts are applied in my library and how WPF works is a bit different.
In terms of WPF, ```RichItemsControl``` inherits ```MultiSelector``` and if you go down the chain you can see it actually inherits ```ItemsControl``` which is a "Control" and his job is to display a list of child items (so you can interact with them like select, drag, resize, whatever you want to do with them or interact with the panel like zoom, pan, scroll and so on).
Now ```RichItemContainer``` comes in which is the "Container" that holds what the "user" wants to display for these childs that ```RichItemsControl``` displays and you can say it's a "Control" as well, but the intent of his usage is to be a shell for what the "user" of the library wants to put in it. So it inherits ```ContentControl``` which can be easily customized through his ```Template``` property where I put a ```ContentPresenter``` so it presents whatever the "user" wants to display in it.

Briefly, this is how I wanted to use these two concepts in the library so the "user" can easily pick them up and understand what the library wants offers. Now, one can argue that everything is a "Control" as this is the class that stays to the top of the chain of visual classes, but that's not the point I believe. Probably some of the things I said aren't familiar to you, but you can read more about them, going into details with everything it's too much.

**Comment by XMJLXMJL** [comment]
Thank you for your detailed explanation. It's very helpful for me to learn WPF.
Sorry for any inconvenience.

**Comment by mircea21S** [comment]
No worries at all, it's nice to see people that want to learn and evolve. And it's also nice that you ended up here on my GitHub repo, even though in my opinion this library is quite advanced in terms of WPF understanding. Good luck with your WPF adventure.
