### ISSUE TITLE
Stretch Image

### ISSUE THREAD

**Issue by RubAccount** [mircea21S/RichCanvas#5]
Hello,
I have to stretch Image instead of mantein aspect ratio. How I can do this in RichCanvas?
Thank you very much
Best regards

**Comment by mircea21S** [comment]
Hello,

You would probably want to set this: : ```Stretch="Fill"``` on the ```Image``` Control in your ```DataTemplate```.
Let me know if that solves it.

Thank you

**Comment by RubAccount** [comment]
Thank you very much. It works properly.
