### ISSUE TITLE
Disable scroll to negative direction

### ISSUE THREAD

**Issue by RubAccount** [mircea21S/RichCanvas#6]
How can I disable scroll in negative directions? In other case how can I limit scroll only in our maximum width and Height setting in RichCanvas?
Thank you.

**Comment by mircea21S** [comment]
So, as I understand you need to limit the scroll extent.
Right now that's not possible, but could be a new feature for the next version.
Let me know if I understood correctly.
Thanks

**Comment by mircea21S** [comment]
New version of library offers this kind of functionality.
If is not what you expected open another issue.

**Comment by RubAccount** [comment]
Hello, 
With new version(v2.1) if we set EnableNegativeScrolling="False" the scroll go anyway in negative direction
Can you check it?
Thank you

**Comment by mircea21S** [comment]
Hello,

Can you please attach some screenshots or maybe explain in more detail what do you mean by negative scrolling?
To me negative scrolling means that the ```ScrollViewer```'s ```VerticalOffset``` property has a positive value.

Right now you cannot go pass the viewport while scrolling up. 
Maybe you want to stop the negative scrolling instantly not when it hits the viewport bottom?

Thank you
